NAME: "ClsNet"

SEED: 0

DATA: 
  ROOT: "/kaggle/input/coco-2017-dataset/coco2017"
  NUM_CLASSES: 81 # For COCO
  MODE: "train"
  BATCH_SIZE: 20
  CROP_SIZE: (321, 321)
  
MODEL:
  WEIGHTS: "vgg_caffe.pth" # From PyCaffe and VGG-16 ImageNet pretrained weights [vgg16_20M.caffemodel] (http://liangchiehchen.com/projects/Init%20Models.html).
  ROI_SIZE: [2,2]
  GRID_SIZE: 4
  GAP: False

SOLVER:
  LR: 1e-3 
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  MAX_ITER: 9000
  MILESTONES: []
